name: CI Setup

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.0.2
      with:
        bun-version: 1.3.1

    - name: Install dependencies
      run: bun install --frozen-lockfile