name: CI Setup
description: Setup Bun and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.0.2
      with:
        bun-version: 1.3.3

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile