packages:
  - apps/*
  - packages/*

overrides:
  apache-arrow: ^18.1.0

autoInstallPeers: true
enableGlobalVirtualStore: true
minimumReleaseAge: 0

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true

catalog:
  "@placemarkio/geojson-rewind": ^1.0.3
  "@types/geojson": ^7946.0.16
  "@types/node": ^24
  dequal: ^2.0.3
  maplibre-gl: ^5.24.0
  pbf: ^5.1.0
  typescript: ^7
  vite: ^8.1.3
