// code generated by @mapbox/pbf v4.0.1 and types merged in by hand

import type Pbf from "pbf"

export type OsmPbfBlob = {
	raw_size?: number
	raw?: Uint8Array
	zlib_data?: Uint8Array
}

export type OsmPbfBlobHeader = {
	type: "OSMHeader" | "OSMData"
	datasize: number
}

export function readBlob(pbf: Pbf, end?: number): OsmPbfBlob {
	return pbf.readFields(
		readBlobField,
		{
			raw_size: 0,
		},
		end,
	)
}
function readBlobField(tag: number, obj: OsmPbfBlob, pbf: Pbf) {
	if (tag === 2) obj.raw_size = pbf.readVarint(true)
	else if (tag === 1) {
		obj.raw = pbf.readBytes()
	} else if (tag === 3) {
		obj.zlib_data = pbf.readBytes()
	}
}
export function writeBlob(obj: OsmPbfBlob, pbf: Pbf) {
	// console.log("writeBlob", obj)
	if (obj.raw_size) pbf.writeVarintField(2, obj.raw_size)
	if (obj.raw != null) pbf.writeBytesField(1, obj.raw)
	if (obj.zlib_data != null) pbf.writeBytesField(3, obj.zlib_data)
}

export function readBlobHeader(pbf: Pbf, end?: number): OsmPbfBlobHeader {
	return pbf.readFields(
		readBlobHeaderField,
		{ type: "OSMData", datasize: 0 },
		end,
	)
}
function readBlobHeaderField(tag: number, obj: OsmPbfBlobHeader, pbf: Pbf) {
	if (tag === 1) obj.type = pbf.readString() as OsmPbfBlobHeader["type"]
	else if (tag === 3) obj.datasize = pbf.readVarint(true)
}
export function writeBlobHeader(obj: OsmPbfBlobHeader, pbf: Pbf) {
	if (obj.type) pbf.writeStringField(1, obj.type)
	if (obj.datasize) pbf.writeVarintField(3, obj.datasize)
}
