// code generated by @mapbox/pbf v4.0.1 and types merged in by hand
import type { PbfReader, PbfWriter } from "pbf";

export type OsmPbfBlob = {
  raw_size?: number;
  raw?: Uint8Array;
  zlib_data?: Uint8Array;
};

export type OsmPbfBlobHeader = {
  type: "OSMHeader" | "OSMData";
  datasize: number;
};

/**
 * Reads an `OsmPbfBlob` message from the current position in the Pbf reader.
 */
export function readBlob(pbf: PbfReader, end?: number): OsmPbfBlob {
  return pbf.readFields(
    readBlobField,
    {
      raw_size: 0,
    },
    end,
  );
}
/**
 * Dispatches individual Blob fields based on their protobuf tag.
 */
function readBlobField(tag: number, obj: OsmPbfBlob, pbf: PbfReader) {
  if (tag === 2) obj.raw_size = pbf.readVarint(true);
  else if (tag === 1) {
    obj.raw = pbf.readBytes();
  } else if (tag === 3) {
    obj.zlib_data = pbf.readBytes();
  }
}
/**
 * Writes an `OsmPbfBlob` message to the provided Pbf writer.
 */
export function writeBlob(obj: OsmPbfBlob, pbf: PbfWriter) {
  if (obj.raw_size) pbf.writeVarintField(2, obj.raw_size);
  if (obj.raw != null) pbf.writeBytesField(1, obj.raw);
  if (obj.zlib_data != null) pbf.writeBytesField(3, obj.zlib_data);
}

/**
 * Reads an `OsmPbfBlobHeader` from the current position in the Pbf reader.
 */
export function readBlobHeader(pbf: PbfReader, end?: number): OsmPbfBlobHeader {
  return pbf.readFields(readBlobHeaderField, { type: "OSMData", datasize: 0 }, end);
}
/**
 * Dispatches individual BlobHeader fields based on their protobuf tag.
 */
function readBlobHeaderField(tag: number, obj: OsmPbfBlobHeader, pbf: PbfReader) {
  if (tag === 1) obj.type = pbf.readString() as OsmPbfBlobHeader["type"];
  else if (tag === 3) obj.datasize = pbf.readVarint(true);
}
/**
 * Writes an `OsmPbfBlobHeader` message to the provided Pbf writer.
 */
export function writeBlobHeader(obj: OsmPbfBlobHeader, pbf: PbfWriter) {
  if (obj.type) pbf.writeStringField(1, obj.type);
  if (obj.datasize) pbf.writeVarintField(3, obj.datasize);
}
