// code generated by @mapbox/pbf v4.0.1 and types merged in by hand
import type Pbf from "pbf"

export type OsmPbfHeaderBBox = {
	left: number
	right: number
	top: number
	bottom: number
}

export type OsmPbfHeaderBlock = {
	bbox?: OsmPbfHeaderBBox
	required_features: string[]
	optional_features: string[]
	writingprogram?: string
	source?: string
	osmosis_replication_timestamp?: number
	osmosis_replication_sequence_number?: number
	osmosis_replication_base_url?: string
}

export interface OsmPbfBlockSettings {
	granularity?: number
	lat_offset?: number
	lon_offset?: number
	date_granularity?: number
}

export interface OsmPbfBlock extends OsmPbfBlockSettings {
	stringtable: OsmPbfStringTable
	primitivegroup: OsmPbfGroup[]
}

export type OsmPbfGroup = {
	nodes: OsmPbfNode[]
	dense?: OsmPbfDenseNodes
	ways: OsmPbfWay[]
	relations: OsmPbfRelation[]
}

export type OsmPbfStringTable = Uint8Array[]

export interface OsmPbfInfo {
	version?: number
	timestamp?: number
	changeset?: number
	uid?: number
	user_sid?: number
	visible?: boolean
}

export type OsmPbfDenseInfo = {
	version: number[]
	timestamp: number[]
	changeset: number[]
	uid: number[]
	user_sid: number[]
	visible: boolean[]
}

export interface OsmPbfPrimitive {
	id: number
	keys: number[]
	vals: number[]
	info?: OsmPbfInfo
}

export interface OsmPbfNode extends OsmPbfPrimitive {
	lat: number
	lon: number
}

export type OsmPbfDenseNodes = {
	id: number[]
	denseinfo?: OsmPbfDenseInfo
	lat: number[]
	lon: number[]
	keys_vals: number[]
}

export interface OsmPbfWay extends OsmPbfPrimitive {
	refs: number[]
}

export interface OsmPbfRelation extends OsmPbfPrimitive {
	roles_sid: number[]
	memids: number[]
	types: number[]
}

/**
 * Reads an `OsmPbfHeaderBlock` message from the provided Pbf reader.
 */
export function readHeaderBlock(pbf: Pbf, end?: number): OsmPbfHeaderBlock {
	return pbf.readFields(
		readHeaderBlockField,
		{
			required_features: [],
			optional_features: [],
		},
		end,
	)
}
/**
 * Populates header block fields based on the protobuf tag encountered.
 */
function readHeaderBlockField(tag: number, obj: OsmPbfHeaderBlock, pbf: Pbf) {
	if (tag === 1) obj.bbox = readHeaderBBox(pbf, pbf.readVarint() + pbf.pos)
	else if (tag === 4) obj.required_features.push(pbf.readString())
	else if (tag === 5) obj.optional_features.push(pbf.readString())
	else if (tag === 16) obj.writingprogram = pbf.readString()
	else if (tag === 17) obj.source = pbf.readString()
	else if (tag === 32) obj.osmosis_replication_timestamp = pbf.readVarint(true)
	else if (tag === 33) {
		obj.osmosis_replication_sequence_number = pbf.readVarint(true)
	} else if (tag === 34) obj.osmosis_replication_base_url = pbf.readString()
}
/**
 * Serializes an `OsmPbfHeaderBlock` message into the Pbf writer.
 */
export function writeHeaderBlock(obj: OsmPbfHeaderBlock, pbf: Pbf) {
	if (obj.bbox) pbf.writeMessage(1, writeHeaderBBox, obj.bbox)
	if (obj.required_features) {
		for (const item of obj.required_features) pbf.writeStringField(4, item)
	}
	if (obj.optional_features) {
		for (const item of obj.optional_features) pbf.writeStringField(5, item)
	}
	if (obj.writingprogram) pbf.writeStringField(16, obj.writingprogram)
	if (obj.source) pbf.writeStringField(17, obj.source)
	if (obj.osmosis_replication_timestamp) {
		pbf.writeVarintField(32, obj.osmosis_replication_timestamp)
	}
	if (obj.osmosis_replication_sequence_number) {
		pbf.writeVarintField(33, obj.osmosis_replication_sequence_number)
	}
	if (obj.osmosis_replication_base_url) {
		pbf.writeStringField(34, obj.osmosis_replication_base_url)
	}
}

/**
 * Reads a header bounding box and converts nanodegrees to degrees.
 */
function readHeaderBBox(pbf: Pbf, end?: number): OsmPbfHeaderBBox {
	return pbf.readFields(
		readHeaderBBoxField,
		{ left: 0, right: 0, top: 0, bottom: 0 },
		end,
	)
}
/**
 * Populates bounding box properties while converting from nanodegrees.
 */
function readHeaderBBoxField(tag: number, obj: OsmPbfHeaderBBox, pbf: Pbf) {
	if (tag === 1) obj.left = pbf.readSVarint() / 1e9
	else if (tag === 2) obj.right = pbf.readSVarint() / 1e9
	else if (tag === 3) obj.top = pbf.readSVarint() / 1e9
	else if (tag === 4) obj.bottom = pbf.readSVarint() / 1e9
}
/**
 * Serializes a header bounding box, converting degrees back to nanodegrees.
 */
function writeHeaderBBox(obj: OsmPbfHeaderBBox, pbf: Pbf) {
	if (obj.left) pbf.writeSVarintField(1, obj.left * 1e9)
	if (obj.right) pbf.writeSVarintField(2, obj.right * 1e9)
	if (obj.top) pbf.writeSVarintField(3, obj.top * 1e9)
	if (obj.bottom) pbf.writeSVarintField(4, obj.bottom * 1e9)
}

/**
 * Reads a primitive block containing string tables and primitive groups.
 */
export function readPrimitiveBlock(pbf: Pbf, end?: number): OsmPbfBlock {
	return pbf.readFields(
		readPrimitiveBlockField,
		{
			stringtable: [],
			primitivegroup: [],
		},
		end,
	)
}

/**
 * Populates primitive block fields based on protobuf tags.
 */
function readPrimitiveBlockField(tag: number, obj: OsmPbfBlock, pbf: Pbf) {
	if (tag === 1) {
		obj.stringtable = readStringTable(pbf, pbf.readVarint() + pbf.pos)
	} else if (tag === 2) {
		obj.primitivegroup.push(readPrimitiveGroup(pbf, pbf.readVarint() + pbf.pos))
	} else if (tag === 17) {
		obj.granularity = pbf.readVarint(true)
		obj.granularity = !obj.granularity ? 1e7 : 1e9 / obj.granularity
	} else if (tag === 19) obj.lat_offset = pbf.readVarint(true) * 1e-9
	else if (tag === 20) obj.lon_offset = pbf.readVarint(true) * 1e-9
	else if (tag === 18) obj.date_granularity = pbf.readVarint(true) ?? 1000
}

/**
 * Serializes a primitive block including its string table and primitive groups.
 */
export function writePrimitiveBlock(obj: OsmPbfBlock, pbf: Pbf) {
	if (obj.stringtable) pbf.writeMessage(1, writeStringTable, obj.stringtable)
	if (obj.primitivegroup) {
		for (const item of obj.primitivegroup) {
			pbf.writeMessage(2, writePrimitiveGroup, item)
		}
	}
	if (obj.granularity != null && obj.granularity !== 1e7) {
		console.error("writeGranularity", obj.granularity)
		pbf.writeVarintField(17, 1e9 / obj.granularity)
	}
	if (obj.lat_offset) pbf.writeVarintField(19, obj.lat_offset / 1e-9)
	if (obj.lon_offset) pbf.writeVarintField(20, obj.lon_offset / 1e-9)
	if (obj.date_granularity != null && obj.date_granularity !== 1000) {
		pbf.writeVarintField(18, obj.date_granularity)
	}
}

/**
 * Reads a primitive group with collections of primitives.
 */
function readPrimitiveGroup(pbf: Pbf, end?: number): OsmPbfGroup {
	return pbf.readFields(
		readPrimitiveGroupField,
		{ nodes: [], ways: [], relations: [] },
		end,
	)
}
/**
 * Populates primitive group collections from protobuf data.
 */
function readPrimitiveGroupField(tag: number, obj: OsmPbfGroup, pbf: Pbf) {
	if (tag === 1) obj.nodes.push(readNode(pbf, pbf.readVarint() + pbf.pos))
	else if (tag === 2) {
		obj.dense = readDenseNodes(pbf, pbf.readVarint() + pbf.pos)
	} else if (tag === 3) obj.ways.push(readWay(pbf, pbf.readVarint() + pbf.pos))
	else if (tag === 4) {
		obj.relations.push(readRelation(pbf, pbf.readVarint() + pbf.pos))
	}
}
/**
 * Serializes a primitive group to protobuf.
 */
function writePrimitiveGroup(obj: OsmPbfGroup, pbf: Pbf) {
	if (obj.nodes) {
		for (const item of obj.nodes) pbf.writeMessage(1, writeNode, item)
	}
	if (obj.dense) pbf.writeMessage(2, writeDenseNodes, obj.dense)
	if (obj.ways) {
		for (const item of obj.ways) pbf.writeMessage(3, writeWay, item)
	}
	if (obj.relations) {
		for (const item of obj.relations) pbf.writeMessage(4, writeRelation, item)
	}
}

/**
 * Reads the shared string table for a primitive block.
 */
function readStringTable(pbf: Pbf, end?: number): OsmPbfStringTable {
	return pbf.readFields(readStringTableField, [], end)
}
/**
 * Appends string table entries as they are encountered.
 */
function readStringTableField(tag: number, obj: Uint8Array[], pbf: Pbf) {
	if (tag === 1) obj.push(pbf.readBytes())
}
/**
 * Serializes string table entries.
 */
function writeStringTable(obj: OsmPbfStringTable, pbf: Pbf) {
	if (obj) {
		for (const item of obj) pbf.writeBytesField(1, item)
	}
}

/**
 * Reads metadata describing a single primitive.
 */
function readInfo(pbf: Pbf, end?: number): OsmPbfInfo {
	return pbf.readFields(readInfoField, {}, end)
}
/**
 * Populates primitive metadata fields.
 */
function readInfoField(tag: number, obj: OsmPbfInfo, pbf: Pbf) {
	if (tag === 1) obj.version = pbf.readVarint(true)
	else if (tag === 2) obj.timestamp = pbf.readVarint(true)
	else if (tag === 3) obj.changeset = pbf.readVarint(true)
	else if (tag === 4) obj.uid = pbf.readVarint(true)
	else if (tag === 5) obj.user_sid = pbf.readVarint()
	else if (tag === 6) obj.visible = pbf.readBoolean()
}
/**
 * Serializes primitive metadata fields.
 */
function writeInfo(obj: OsmPbfInfo, pbf: Pbf) {
	if (obj.version != null && obj.version !== -1) {
		pbf.writeVarintField(1, obj.version)
	}
	if (obj.timestamp) pbf.writeVarintField(2, obj.timestamp)
	if (obj.changeset) pbf.writeVarintField(3, obj.changeset)
	if (obj.uid) pbf.writeVarintField(4, obj.uid)
	if (obj.user_sid) pbf.writeVarintField(5, obj.user_sid)
	if (obj.visible) pbf.writeBooleanField(6, obj.visible)
}

/**
 * Reads dense node metadata collections.
 */
function readDenseInfo(pbf: Pbf, end?: number): OsmPbfDenseInfo {
	return pbf.readFields(
		readDenseInfoField,
		{
			version: [],
			timestamp: [],
			changeset: [],
			uid: [],
			user_sid: [],
			visible: [],
		},
		end,
	)
}
/**
 * Populates dense node metadata arrays from packed fields.
 */
function readDenseInfoField(tag: number, obj: OsmPbfDenseInfo, pbf: Pbf) {
	if (tag === 1) pbf.readPackedVarint(obj.version, true)
	else if (tag === 2) pbf.readPackedSVarint(obj.timestamp)
	else if (tag === 3) pbf.readPackedSVarint(obj.changeset)
	else if (tag === 4) pbf.readPackedSVarint(obj.uid)
	else if (tag === 5) pbf.readPackedSVarint(obj.user_sid)
	else if (tag === 6) pbf.readPackedBoolean(obj.visible)
}
/**
 * Serializes dense node metadata arrays.
 */
function writeDenseInfo(obj: OsmPbfDenseInfo, pbf: Pbf) {
	if (obj.version) pbf.writePackedVarint(1, obj.version)
	if (obj.timestamp) pbf.writePackedSVarint(2, obj.timestamp)
	if (obj.changeset) pbf.writePackedSVarint(3, obj.changeset)
	if (obj.uid) pbf.writePackedSVarint(4, obj.uid)
	if (obj.user_sid) pbf.writePackedSVarint(5, obj.user_sid)
	if (obj.visible) pbf.writePackedBoolean(6, obj.visible)
}

/**
 * Reads a node primitive from the protobuf stream.
 */
function readNode(pbf: Pbf, end?: number): OsmPbfNode {
	return pbf.readFields(
		readNodeField,
		{ id: 0, keys: [], vals: [], lat: 0, lon: 0 },
		end,
	)
}
/**
 * Populates node fields based on protobuf tags.
 */
function readNodeField(tag: number, obj: OsmPbfNode, pbf: Pbf) {
	if (tag === 1) obj.id = pbf.readSVarint()
	else if (tag === 2) pbf.readPackedVarint(obj.keys)
	else if (tag === 3) pbf.readPackedVarint(obj.vals)
	else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos)
	else if (tag === 8) obj.lat = pbf.readSVarint()
	else if (tag === 9) obj.lon = pbf.readSVarint()
}
/**
 * Serializes a node primitive to protobuf.
 */
function writeNode(obj: OsmPbfNode, pbf: Pbf) {
	if (obj.id) pbf.writeSVarintField(1, obj.id)
	if (obj.keys) pbf.writePackedVarint(2, obj.keys)
	if (obj.vals) pbf.writePackedVarint(3, obj.vals)
	if (obj.info) pbf.writeMessage(4, writeInfo, obj.info)
	if (obj.lat) pbf.writeSVarintField(8, obj.lat)
	if (obj.lon) pbf.writeSVarintField(9, obj.lon)
}

/**
 * Reads dense node collections from the protobuf stream.
 */
function readDenseNodes(pbf: Pbf, end?: number): OsmPbfDenseNodes {
	return pbf.readFields(
		readDenseNodesField,
		{ id: [], lat: [], lon: [], keys_vals: [] },
		end,
	)
}
/**
 * Populates dense node arrays using packed encoding.
 */
function readDenseNodesField(tag: number, obj: OsmPbfDenseNodes, pbf: Pbf) {
	if (tag === 1) pbf.readPackedSVarint(obj.id)
	else if (tag === 5) {
		obj.denseinfo = readDenseInfo(pbf, pbf.readVarint() + pbf.pos)
	} else if (tag === 8) pbf.readPackedSVarint(obj.lat)
	else if (tag === 9) pbf.readPackedSVarint(obj.lon)
	else if (tag === 10) pbf.readPackedVarint(obj.keys_vals, true)
}
/**
 * Serializes dense node collections back to protobuf.
 */
function writeDenseNodes(obj: OsmPbfDenseNodes, pbf: Pbf) {
	if (obj.id) pbf.writePackedSVarint(1, obj.id)
	if (obj.denseinfo) pbf.writeMessage(5, writeDenseInfo, obj.denseinfo)
	if (obj.lat) pbf.writePackedSVarint(8, obj.lat)
	if (obj.lon) pbf.writePackedSVarint(9, obj.lon)
	if (obj.keys_vals) pbf.writePackedVarint(10, obj.keys_vals)
}

/**
 * Reads a way primitive from the protobuf stream.
 */
function readWay(pbf: Pbf, end?: number): OsmPbfWay {
	return pbf.readFields(
		readWayField,
		{ id: 0, keys: [], vals: [], refs: [], lat: [], lon: [] },
		end,
	)
}
/**
 * Populates way fields based on protobuf tags.
 */
function readWayField(tag: number, obj: OsmPbfWay, pbf: Pbf) {
	if (tag === 1) obj.id = pbf.readVarint(true)
	else if (tag === 2) pbf.readPackedVarint(obj.keys)
	else if (tag === 3) pbf.readPackedVarint(obj.vals)
	else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos)
	else if (tag === 8) pbf.readPackedSVarint(obj.refs)
}
/**
 * Serializes a way primitive to protobuf.
 */
function writeWay(obj: OsmPbfWay, pbf: Pbf) {
	if (obj.id) pbf.writeVarintField(1, obj.id)
	if (obj.keys) pbf.writePackedVarint(2, obj.keys)
	if (obj.vals) pbf.writePackedVarint(3, obj.vals)
	if (obj.info) pbf.writeMessage(4, writeInfo, obj.info)
	if (obj.refs) pbf.writePackedSVarint(8, obj.refs)
}

/**
 * Reads a relation primitive from the protobuf stream.
 */
function readRelation(pbf: Pbf, end?: number): OsmPbfRelation {
	return pbf.readFields(
		readRelationField,
		{
			id: 0,
			keys: [],
			vals: [],
			roles_sid: [],
			memids: [],
			types: [],
		},
		end,
	)
}
/**
 * Populates relation fields based on protobuf tags.
 */
function readRelationField(tag: number, obj: OsmPbfRelation, pbf: Pbf) {
	if (tag === 1) obj.id = pbf.readVarint(true)
	else if (tag === 2) pbf.readPackedVarint(obj.keys)
	else if (tag === 3) pbf.readPackedVarint(obj.vals)
	else if (tag === 4) obj.info = readInfo(pbf, pbf.readVarint() + pbf.pos)
	else if (tag === 8) pbf.readPackedVarint(obj.roles_sid, true)
	else if (tag === 9) pbf.readPackedSVarint(obj.memids)
	else if (tag === 10) pbf.readPackedVarint(obj.types)
}
/**
 * Serializes a relation primitive to protobuf.
 */
function writeRelation(obj: OsmPbfRelation, pbf: Pbf) {
	if (obj.id) pbf.writeVarintField(1, obj.id)
	if (obj.keys) pbf.writePackedVarint(2, obj.keys)
	if (obj.vals) pbf.writePackedVarint(3, obj.vals)
	if (obj.info) pbf.writeMessage(4, writeInfo, obj.info)
	if (obj.roles_sid) pbf.writePackedVarint(8, obj.roles_sid)
	if (obj.memids) pbf.writePackedSVarint(9, obj.memids)
	if (obj.types) pbf.writePackedVarint(10, obj.types)
}
