name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CI: true

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: ./.github/actions/setup
      - uses: ./.github/actions/checks
